[build]
builder = "nixpacks"

[deploy]
startCommand = "honcho start -f Procfile"
healthcheckPath = "/"
healthcheckTimeout = 100

[nixpacks]
aptPackages = ["libgl1-mesa-glx", "libglib2.0-0", "libsm6", "libxext6", "libxrender-dev", "libgl1"]

[env]
LD_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu:$LD_LIBRARY_PATH"
